"""add email_enc_password

Revision ID: 005f806104d8
Revises: 54a97bc4acd2
Create Date: 2025-11-23 03:22:55.466169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005f806104d8'
down_revision = '54a97bc4acd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_enc_password', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.drop_column('email_enc_password')

    # ### end Alembic commands ###
